base_out_of_range: "Please enter numeric bases only between 2 and 36."
bad_number: "Error, please enter a valid number to convert."
numeric_base_conversion: "Numerical base conversion"
original_number_in_base: "Original number in base"
converted_number_in_base: "Number converted to base"