name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Kirino
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_LOGIN}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd Kirino
            git reset --hard 2>> ./.tmp/deploy.log
            git pull < "${{secrets.SSH_LOGIN}}\n${{secrets.SSH_GITHUB_TOKEN}}" 2>> ./.tmp/deploy.log
            pm2 restart kirino 2>> ./.tmp/deploy.log